# Generated by Django 5.2.10 on 2026-01-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='mission',
            field=models.TextField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='vision',
            field=models.TextField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=2000),
            preserve_default=False,
        ),
    ]
